version: '3'

services:
  frontend:
    build:
      context: ./ui
    ports:
      - "8501:8501"  # Adjust port as necessary
    depends_on:
      - backend

  backend:
    build:
      context: ./  # Set the build context to the root directory
    ports:
      - "8000:8000"
    volumes:
      - ./API:/app/API
      - ./embeddings:/app/embeddings
      - ./collected-data:/app/collected-data